CREATE TABLE IF NOT EXISTS users(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    name VARCHAR(200) NOT NULL,
    email VARCHAR(400) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activated BOOL NOT NULL,
    version INT NOT NULL DEFAULT 1
);
